---
# code: language=ansible
- name: Create/update setting file
  ansible.builtin.template:
    src: config.toml.j2
    dest: "{{ meilisearch_home }}/config.toml"
    owner: "{{ meilisearch_user }}"
    group: "{{ meilisearch_group }}"
    mode: "0644"
  notify: Restart meilisearch
