---
# code: language=ansible
# - name: Restart meilisearch
#   ansible.builtin.systemd:
#     state: restarted
#     name: meilisearch
# - name: Reload meilisearch
#   ansible.builtin.systemd:
#     state: reloaded
#     name: meilisearch
