---
# code: language=ansible
- name: Service meilisearch is active and enabled on system startup
  ansible.builtin.systemd:
    name: meilisearch
    state: started
    enabled: true
# - name: allow meilisearch port
#   community.general.ufw:
#     rule: allow
#     port: "123456"
