---
# code: language=ansible
- name: Create/update systemd unit file
  ansible.builtin.template:
    src: meilisearch.service.j2
    dest: /lib/systemd/system/meilisearch.service
    mode: "0644"
  notify: Restart meilisearch
- name: Service Meilisearch is active and enabled on system startup
  ansible.builtin.systemd:
    daemon_reload: true
    name: meilisearch
    state: started
    enabled: true
- name: Allow meilisearch port
  community.general.ufw:
    rule: allow
    port: "{{ meilisearch_port }}"
  when: meilisearch_allow_connect_other_host | default(false)
