---
# code: language=ansible
- name: Set Install version variable
  when: meilisearch_version == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_reauest_header) }}"
      vars:
        merge_reauest_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/meilisearch/meilisearch/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: Set tbls_version variable
      ansible.builtin.set_fact:
        meilisearch_version: "{{ latest_releases.json.tag_name }}"
- name: Set pckage file variable
  ansible.builtin.set_fact:
    download_file: meilisearch-{{ ansible_facts.system | lower }}-{{ architecture_files[ansible_facts['architecture']] }}
  vars:
    architecture_files:
      x86_64: amd64
      aarch64: aarch64
- name: Install Meilisearch
  ansible.builtin.get_url:
    url: https://github.com/meilisearch/meilisearch/releases/download/{{ meilisearch_version }}/{{ download_file }}
    dest: "{{ meilisearch_bin_dir }}/meilisearch"
    mode: "0755"
